[tools]
aws-vault = "7.2.0"
awscli = "2.15.34"
helm = "3.14.3"
kubectl = "1.28.8"
kubectx = "0.9.5"
python = "3.12.2"
go = "1.22.2"
terraform = "1.7.5"
terraform-docs = "0.17.0"
helmfile = "0.163.1"
usage = "latest"
argocd = "2.10.6"
pre-commit = "3.7.0"
node = "21.7.3"
updatecli = "latest"
kind = "0.23.0"
